"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, LoaderCircle, MapPin, Search, Sprout, Trophy, UsersRound, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Drive = { id: string; municipality_id: string | null; ward_id: string | null; title: string; description: string | null; location: string | null; start_time: string; end_time: string | null; max_volunteers: number | null; created_by: string | null; created_at: string };
type Volunteer = { id: string; cleanup_drive_id: string; user_id: string; joined_at: string };
type Municipality = { id: string; name: string; state: string; district: string | null };
type Ward = { id: string; municipality_id: string; name: string; ward_number: string | null };

export function CommunityActivities({ userId, userName, drives: initialDrives, volunteers: initialVolunteers, municipalities, wards }: { userId: string; userName: string | null; drives: Drive[]; volunteers: Volunteer[]; municipalities: Municipality[]; wards: Ward[] }) {
  const [drives] = useState(initialDrives);
  const [volunteers, setVolunteers] = useState(initialVolunteers);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Drive | null>(null);
  const [joining, setJoining] = useState(false);
  const [feedback, setFeedback] = useState<string | null>(null);

  const [currentTime] = useState(() => Date.now());
  const membersFor = (driveId: string) => volunteers.filter((entry) => entry.cleanup_drive_id === driveId);
  const joined = (driveId: string) => membersFor(driveId).some((entry) => entry.user_id === userId);
  const isCompleted = (drive: Drive) => Boolean(drive.end_time && new Date(drive.end_time).getTime() < currentTime);
  const upcoming = drives.filter((drive) => !isCompleted(drive));
  const visible = upcoming.filter((drive) => `${drive.title} ${drive.location ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const myDrives = drives.filter((drive) => joined(drive.id));
  const badges = myDrives.filter(isCompleted);

  async function join(drive: Drive) {
    if (joined(drive.id) || joining) return;
    const count = membersFor(drive.id).length;
    if (drive.max_volunteers !== null && count >= drive.max_volunteers) {
      setFeedback("This activity has reached its volunteer limit.");
      return;
    }
    setJoining(true);
    setFeedback(null);
    const { data, error } = await createClient()
      .from("cleanup_volunteers")
      .insert({ cleanup_drive_id: drive.id, user_id: userId })
      .select("id,cleanup_drive_id,user_id,joined_at")
      .single();
    setJoining(false);
    if (error || !data) {
      setFeedback(error?.code === "23505" ? "You’re already registered for this activity." : error?.message || "We couldn’t register you. Please try again.");
      return;
    }
    setVolunteers((current) => [...current, data as Volunteer]);
    setFeedback(`You’re registered for ${drive.title}. See you there!`);
  }

  return <main className="min-h-screen bg-stone-50 px-4 py-8 text-slate-900 dark:bg-slate-950 dark:text-slate-100 sm:px-7">
    <div className="mx-auto max-w-7xl">
      <div className="flex items-center justify-between gap-4"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700 dark:text-emerald-400"><ArrowLeft className="size-4" /> Back to dashboard</Link><Link href="/profile" className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold hover:border-emerald-300 dark:border-slate-800 dark:bg-slate-900">My profile</Link></div>
      <section className="hero-panel mt-7 rounded-3xl px-6 py-8 text-white sm:px-8">
        <div className="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="inline-flex items-center gap-2 text-sm font-bold text-emerald-100"><Sprout className="size-4" /> COMMUNITY ACTIVITIES</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Make your community cleaner.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-100 sm:text-base">{userName ? `Join neighbours like ${userName.split(" ")[0]} in local cleanup drives,` : "Join local cleanup drives,"} volunteer alongside your community, and celebrate the impact you make together.</p></div><div className="flex gap-3"><ImpactStat icon={<UsersRound className="size-5" />} value={myDrives.length} label="Activities joined" /><ImpactStat icon={<Trophy className="size-5" />} value={badges.length} label="Badges earned" /></div></div>
      </section>
      {feedback ? <div role="status" className="mt-4 flex items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-100"><span>{feedback}</span><button onClick={() => setFeedback(null)} aria-label="Dismiss"><X className="size-4" /></button></div> : null}
      <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold tracking-tight">Upcoming activities</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Find a local drive and lend a hand.</p></div><label className="relative w-full sm:w-80"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-slate-400" /><span className="sr-only">Search activities</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activities or locations" className="field py-2.5 pl-9" /></label></div>
        {visible.length ? <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((drive) => <ActivityCard key={drive.id} drive={drive} municipality={municipalities.find((item) => item.id === drive.municipality_id)} ward={wards.find((item) => item.id === drive.ward_id)} count={membersFor(drive.id).length} joined={joined(drive.id)} onView={() => setSelected(drive)} />)}</div> : <EmptyActivities query={query} />}
      </section>
      <section className="mt-10"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300"><Trophy className="size-5" /></span><div><h2 className="text-2xl font-bold tracking-tight">My activities</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Your registrations and community participation badges.</p></div></div>
        {myDrives.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{myDrives.map((drive) => isCompleted(drive) ? <ParticipationBadge key={drive.id} drive={drive} /> : <MyActivityCard key={drive.id} drive={drive} onView={() => setSelected(drive)} />)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-9 text-center dark:border-slate-700 dark:bg-slate-900"><Sprout className="mx-auto size-8 text-emerald-700" /><h3 className="mt-3 font-bold">Your community journey starts here</h3><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-slate-500">Join an upcoming activity to keep it handy here and earn a participation badge when it is completed.</p></div>}
      </section>
    </div>
    {selected ? <ActivityDialog drive={selected} count={membersFor(selected.id).length} joined={joined(selected.id)} municipality={municipalities.find((item) => item.id === selected.municipality_id)} ward={wards.find((item) => item.id === selected.ward_id)} joining={joining} onJoin={() => join(selected)} onClose={() => setSelected(null)} /> : null}
  </main>;
}

function ActivityCard({ drive, municipality, ward, count, joined, onView }: { drive: Drive; municipality?: Municipality; ward?: Ward; count: number; joined: boolean; onView: () => void }) { return <article className="complaint-card flex flex-col rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"><Sprout className="size-5" /></span>{joined ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-200"><CheckCircle2 className="size-3.5" /> Registered</span> : null}</div><h3 className="mt-5 text-lg font-bold">{drive.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{drive.description || "A neighbourhood activity to make shared spaces cleaner and healthier."}</p><div className="mt-5 space-y-2 text-sm text-slate-600 dark:text-slate-400"><Info icon={<MapPin className="size-4" />} text={drive.location || [municipality?.name, ward ? `${ward.ward_number ? `Ward ${ward.ward_number} · ` : ""}${ward.name}` : null].filter(Boolean).join(" · ") || "Location to be confirmed"} /><Info icon={<CalendarDays className="size-4" />} text={dateTime(drive.start_time).date} /><Info icon={<Clock3 className="size-4" />} text={dateTime(drive.start_time).time} /><Info icon={<UsersRound className="size-4" />} text={`${count}${drive.max_volunteers !== null ? `/${drive.max_volunteers}` : ""} volunteers joined`} /></div><button onClick={onView} className="mt-6 min-h-11 rounded-xl border border-emerald-200 px-4 text-sm font-bold text-emerald-800 hover:bg-emerald-50 dark:border-emerald-900 dark:text-emerald-300 dark:hover:bg-emerald-950/30">View details</button></article>; }
function ActivityDialog({ drive, count, joined, municipality, ward, joining, onJoin, onClose }: { drive: Drive; count: number; joined: boolean; municipality?: Municipality; ward?: Ward; joining: boolean; onJoin: () => void; onClose: () => void }) { const full = drive.max_volunteers !== null && count >= drive.max_volunteers; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-labelledby="activity-title"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl sm:p-7 dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><span className="grid size-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40"><Sprout className="size-5" /></span><h2 id="activity-title" className="mt-4 text-2xl font-bold">{drive.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{drive.description || "Join your neighbours for a positive, hands-on community cleanup."}</p></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Close activity details"><X /></button></div><div className="mt-6 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm dark:bg-slate-800/60"><Info icon={<MapPin className="size-4" />} text={drive.location || [municipality?.name, ward?.name].filter(Boolean).join(" · ") || "Location to be confirmed"} /><Info icon={<CalendarDays className="size-4" />} text={dateTime(drive.start_time).date} /><Info icon={<Clock3 className="size-4" />} text={`${dateTime(drive.start_time).time}${drive.end_time ? ` – ${dateTime(drive.end_time).time}` : ""}`} /><Info icon={<UsersRound className="size-4" />} text={`${count}${drive.max_volunteers !== null ? ` of ${drive.max_volunteers}` : ""} volunteers registered`} /></div><div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4 dark:border-emerald-900 dark:bg-emerald-950/25"><p className="font-bold text-emerald-950 dark:text-emerald-100">Join this cleanup drive</p><p className="mt-1 text-sm leading-6 text-emerald-900/80 dark:text-emerald-200">You’ll be registered using your Swachh Connect profile—no additional details needed.</p></div><button disabled={joined || full || joining} onClick={onJoin} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-60">{joining ? <LoaderCircle className="size-4 animate-spin" /> : joined ? <CheckCircle2 className="size-4" /> : <Sprout className="size-4" />}{joining ? "Registering…" : joined ? "You’re registered" : full ? "Activity is full" : "Confirm participation"}</button></section></div>; }
function MyActivityCard({ drive, onView }: { drive: Drive; onView: () => void }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40"><Sprout className="size-5" /></span><span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-200"><CheckCircle2 className="size-3.5" /> Registered</span></div><h3 className="mt-4 font-bold">{drive.title}</h3><p className="mt-1 text-sm text-slate-500">{dateTime(drive.start_time).date} · {dateTime(drive.start_time).time}</p><button onClick={onView} className="mt-4 text-sm font-bold text-emerald-700 hover:text-emerald-800 dark:text-emerald-400">View details</button></article>; }
function ParticipationBadge({ drive }: { drive: Drive }) { return <article className="relative overflow-hidden rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 via-white to-emerald-50 p-5 dark:border-amber-900/60 dark:from-amber-950/30 dark:via-slate-900 dark:to-emerald-950/20"><Trophy className="absolute -right-3 -top-3 size-24 text-amber-200/70 dark:text-amber-500/10" /><div className="relative"><span className="grid size-12 place-items-center rounded-2xl bg-amber-100 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300"><Trophy className="size-6" /></span><p className="mt-4 text-xs font-extrabold tracking-[.14em] text-amber-800 uppercase dark:text-amber-300">Cleanup hero</p><h3 className="mt-1 text-lg font-bold">{drive.title}</h3><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{dateTime(drive.start_time).monthYear} · Participation badge earned</p></div></article>; }
function ImpactStat({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 backdrop-blur"><span className="flex items-center gap-2 text-emerald-100">{icon}<b className="text-xl text-white">{value}</b></span><span className="mt-1 block text-xs text-emerald-100">{label}</span></div>; }
function Info({ icon, text }: { icon: React.ReactNode; text: string }) { return <p className="flex items-start gap-2"><span className="mt-0.5 text-emerald-700 dark:text-emerald-400">{icon}</span><span>{text}</span></p>; }
function EmptyActivities({ query }: { query: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900"><Sprout className="mx-auto size-9 text-emerald-700" /><h3 className="mt-3 font-bold">{query ? "No matching activities" : "No upcoming activities yet"}</h3><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-slate-500">{query ? "Try another activity or location." : "When your municipality adds a cleanup drive, it will appear here."}</p></div>; }
function dateTime(value: string) { const date = new Date(value); return { date: new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }).format(date), time: new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(date), monthYear: new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(date) }; }
